/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthCamp;

import ReliefSystem.Ecosystem;
import ReliefSystem.HealthCamp.HealthCamp;
import ReliefSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 18578
 */
public class ManageOrgInfo extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrgInfo
     */
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;

    public ManageOrgInfo(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblorgname = new javax.swing.JLabel();
        txtorgname = new javax.swing.JTextField();
        lblorgowner = new javax.swing.JLabel();
        txtorgowner = new javax.swing.JTextField();
        lblorgadd = new javax.swing.JLabel();
        txtorgadd = new javax.swing.JTextField();
        lblphonenumber = new javax.swing.JLabel();
        txtphonenumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblorgname.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblorgname.setForeground(new java.awt.Color(0, 102, 102));
        lblorgname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblorgname.setText("NAME");
        add(lblorgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 31));

        txtorgname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtorgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 190, 30));

        lblorgowner.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblorgowner.setForeground(new java.awt.Color(0, 102, 102));
        lblorgowner.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblorgowner.setText("OWNER");
        add(lblorgowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 90, 24));

        txtorgowner.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtorgowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 190, 30));

        lblorgadd.setBackground(new java.awt.Color(255, 255, 255));
        lblorgadd.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblorgadd.setForeground(new java.awt.Color(0, 102, 102));
        lblorgadd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblorgadd.setText("ADDRESS");
        add(lblorgadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 130, 30));

        txtorgadd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtorgadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 190, 30));

        lblphonenumber.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lblphonenumber.setForeground(new java.awt.Color(0, 102, 102));
        lblphonenumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblphonenumber.setText("PHONE NUMBER");
        add(lblphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 120, 22));

        txtphonenumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 190, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ORGANISATION INFORMATION ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 350, 50));

        btnsave.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnsave.setForeground(new java.awt.Color(0, 102, 102));
        btnsave.setText("SAVE");
        btnsave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 120, 40));

        btnupdate.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 102, 102));
        btnupdate.setText("UPDATE");
        btnupdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 120, 40));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/org_info.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 850, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if(validateInputFields()){
        for (HealthCamp healthCamp : system.getHealthCampDirectory().getHealthCampDirectory()) {
            System.out.println("account username : " + account.getUsername());
            System.out.println("health camp username : " + healthCamp.getUsername());
            if (healthCamp.getUsername().equals(account.getUsername())) {

                system.getHealthCampDirectory().updateHealthCampInfo(healthCamp, txtorgowner.getText(), txtorgadd.getText(), txtphonenumber.getText(), txtorgname.getText());

            }
        }

        btnupdate.setEnabled(true);
        txtorgname.setEnabled(false);
        txtorgowner.setEnabled(false);
        txtorgadd.setEnabled(false);
        txtphonenumber.setEnabled(false);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        txtorgname.setEnabled(true);
        txtorgowner.setEnabled(true);
        txtorgadd.setEnabled(true);
        txtphonenumber.setEnabled(true);
        btnupdate.setEnabled(false);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblorgadd;
    private javax.swing.JLabel lblorgname;
    private javax.swing.JLabel lblorgowner;
    private javax.swing.JLabel lblphonenumber;
    private javax.swing.JTextField txtorgadd;
    private javax.swing.JTextField txtorgname;
    private javax.swing.JTextField txtorgowner;
    private javax.swing.JTextField txtphonenumber;
    // End of variables declaration//GEN-END:variables
 private boolean validateInputFields() {

        Pattern p = Pattern.compile("^[A-Za-z0-9 ]+$");
        Matcher m = p.matcher(txtorgowner.getText());
        Pattern p7 = Pattern.compile("^[A-Za-z0-9]+$");
        Matcher m7 = p7.matcher(txtorgname.getText());
        Pattern p1 = Pattern.compile("^[A-Za-z0-9]+$");
       Matcher m1 = p1.matcher(txtorgadd.getText());
       Pattern p2 = Pattern.compile("^[0-9]{10,10}+$");
       Matcher m2 = p2.matcher(txtphonenumber.getText());

// Matcher m1 = p1.matcher(manuyeartxt.getText());
// Pattern p2 = Pattern.compile("[0-9]");
// Matcher m2 = p2.matcher(serialnumtxt.getText());
// Pattern p3 = Pattern.compile("[0-9]");
// Matcher m3 = p4.matcher(citytxt.getText());
        if (!m.matches()) {

            JOptionPane.showMessageDialog(this, "Please enter correct input format for owner");
            return false;
        } else if (!m7.matches()) {

            JOptionPane.showMessageDialog(this, "Please enter correct input format for orgname ");
            return false;
        }
        else if (!m1.matches()) {

            JOptionPane.showMessageDialog(this, "Please enter correct input format for address ");
            return false;
        }
         else if (!m2.matches()) {

        JOptionPane.showMessageDialog(this, "Please enter correct input format for phonenumber");
            return false; 
         }
        else {
            return true;
        }
    }
}

