/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospiitalAdmin;

import ReliefSystem.Ecosystem;
import ReliefSystem.FundRaising.FundRaising;
import ReliefSystem.PetVolunteer.PetVolunteer;
import ReliefSystem.UserAccount.UserAccount;
import ReliefSystem.Vet.Vet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 18578
 */
public class ManagePetInfo extends javax.swing.JPanel {

    /**
     * Creates new form ManagePetInfo
     */
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;
    public ManagePetInfo(JPanel userProcessContainer,UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.system = system;
        this.account = account;
        populatePetInfo();
    }

    public void populatePetInfo() {
        
        DefaultTableModel tablemodel = (DefaultTableModel) tblpetinfo.getModel();
        tablemodel.setRowCount(0);
        for (PetVolunteer petVolunteer : system.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
            if (petVolunteer.getHospitalName().equals(account.getName())) {
                Object[] row = new Object[5];
                row[0] = petVolunteer;
                row[1] = petVolunteer.getName();
//                row[2] = petVolunteer.getUsername();
                row[2] = petVolunteer.getPetType();
                row[3] = petVolunteer.getHealthCamp();
                row[4] = petVolunteer.getLabResultStatus() == null ? "N/A" : petVolunteer.getLabResultStatus();
                tablemodel.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblpetinfo = new javax.swing.JTable();
        btnAssignPetOwnerToVet = new javax.swing.JButton();
        btnaddfundraiser = new javax.swing.JButton();
        lblVet = new javax.swing.JLabel();
        txtvet = new javax.swing.JTextField();

        tblpetinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "pet username", "pet owner", "pet type", "Health Camp", "Lab result status"
            }
        ));
        jScrollPane1.setViewportView(tblpetinfo);

        btnAssignPetOwnerToVet.setText("Add vet");
        btnAssignPetOwnerToVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignPetOwnerToVetActionPerformed(evt);
            }
        });

        btnaddfundraiser.setText("Add Fundraiser");
        btnaddfundraiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddfundraiserActionPerformed(evt);
            }
        });

        lblVet.setText("Vet ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnaddfundraiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAssignPetOwnerToVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lblVet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtvet, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVet)
                    .addComponent(txtvet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAssignPetOwnerToVet)
                .addGap(18, 18, 18)
                .addComponent(btnaddfundraiser)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignPetOwnerToVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignPetOwnerToVetActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblpetinfo.getSelectedRow();
        PetVolunteer vetSelected = (PetVolunteer) tblpetinfo.getValueAt(selectedRow, 0);
        String vetPetOwner = vetSelected.getName();
        String vetPetType = vetSelected.getPetType();
        String vetHealthCamp = vetSelected.getHealthCamp();
        String vetHospitalName = vetSelected.getHospitalName();
        for(Vet vet: system.getVetDirectory().getVetDirectory()) {
            if(vet.getUsername().equals(txtvet.getText())){
                system.getVetDirectory().updateVetInfo(vet, vetPetOwner, vetPetType, vetHealthCamp, vetHospitalName);
            }
        }
        JOptionPane.showMessageDialog(this, "Successfuly assigned vet");
    }//GEN-LAST:event_btnAssignPetOwnerToVetActionPerformed

    private void btnaddfundraiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddfundraiserActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblpetinfo.getSelectedRow();
        PetVolunteer vetSelected = (PetVolunteer) tblpetinfo.getValueAt(selectedRow, 0);
        String vetPetOwner = vetSelected.getName();
        String vetPetType = vetSelected.getPetType();
        String vetHealthCamp = vetSelected.getHealthCamp();
        String vetHospitalName = vetSelected.getHospitalName();
        for(FundRaising fundRaising: system.getFundRaisingDirectory().getFundRaisingDirectory()) {
            system.getFundRaisingDirectory().updateFundRaisingInfo(fundRaising, vetPetOwner, vetPetType, vetHealthCamp, vetHospitalName);
            System.out.println("Fund raising agency updated sucessfully");
        }
    }//GEN-LAST:event_btnaddfundraiserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignPetOwnerToVet;
    private javax.swing.JButton btnaddfundraiser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVet;
    private javax.swing.JTable tblpetinfo;
    private javax.swing.JTextField txtvet;
    // End of variables declaration//GEN-END:variables
}
