/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital;

import ReliefSystem.Ecosystem;
import ReliefSystem.LabAssistant.LabAssistant;
import ReliefSystem.PetVolunteer.PetVolunteer;
import ReliefSystem.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 18578
 */
public class LabAssitantWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form LabAssitantWorkArea
     */
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;

    public LabAssitantWorkArea(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tbllabassitant.getModel();
        tablemodel.setRowCount(0);
        for (LabAssistant labAssistant : system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            if (labAssistant.getUsername().equals(account.getUsername())) {
                System.out.println("Lab assistant : " + labAssistant.getUsername());
                System.out.println("Lab assistant : " + labAssistant.getPetOwner());
                System.out.println("Lab assistant : " + labAssistant.getPetType());
                Object[] row = new Object[4];
                row[0] = labAssistant.getPetOwner();
                row[1] = labAssistant.getPetType();
                row[2] = labAssistant.getHealthCamp();
                row[3] = labAssistant.getLabResultStatus() == null ? "N/A" : labAssistant.getLabResultStatus();
                tablemodel.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbllabassitant = new javax.swing.JTable();
        lbllabresult = new javax.swing.JLabel();
        txtlabresult = new javax.swing.JTextField();
        btnchangestatus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbllabassitant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pet Owner", "Pet Type", "Health Camp", "Test Result"
            }
        ));
        jScrollPane1.setViewportView(tbllabassitant);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 375, 95));

        lbllabresult.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lbllabresult.setForeground(new java.awt.Color(0, 102, 102));
        lbllabresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllabresult.setText("LAB RESULT");
        add(lbllabresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 105, 30));

        txtlabresult.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        add(txtlabresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 130, 30));

        btnchangestatus.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnchangestatus.setForeground(new java.awt.Color(0, 102, 102));
        btnchangestatus.setText("CHANGE STATUS");
        btnchangestatus.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        btnchangestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangestatusActionPerformed(evt);
            }
        });
        add(btnchangestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 140, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME LAB ASSISTANT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 370, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcome_lab_assistant.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 40, 550, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnchangestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangestatusActionPerformed
        // TODO add your handling code here:
        String status = txtlabresult.getText();
        for(LabAssistant labAssistant: system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            system.getLabAssistantDirectory().updateLabAssistantTestResult(labAssistant, status);
            System.out.println("Lab result updated successfully");
        }
        for(LabAssistant labAssistant: system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            for(PetVolunteer petVolunteer: system.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
                if(petVolunteer.getName().equals(labAssistant.getPetOwner())){
                    system.getPetVolunteerDirectory().updatePetVolunteerLabStatus(petVolunteer, status);
                    System.out.println("Lab status updated successfully");
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Successfully updated lab results");
        populateTable();
    }//GEN-LAST:event_btnchangestatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchangestatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllabresult;
    private javax.swing.JTable tbllabassitant;
    private javax.swing.JTextField txtlabresult;
    // End of variables declaration//GEN-END:variables
}
