/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital;

import ReliefSystem.Ecosystem;
import ReliefSystem.LabAssistant.LabAssistant;
import ReliefSystem.PetVolunteer.PetVolunteer;
import ReliefSystem.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 18578
 */
public class LabAssitantWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form LabAssitantWorkArea
     */
    JPanel userProcessContainer;
    Ecosystem system;
    private UserAccount account;

    public LabAssitantWorkArea(JPanel userProcessContainer, UserAccount account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tbllabassitant.getModel();
        tablemodel.setRowCount(0);
        for (LabAssistant labAssistant : system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            if (labAssistant.getUsername().equals(account.getUsername())) {
                System.out.println("Lab assistant : " + labAssistant.getUsername());
                System.out.println("Lab assistant : " + labAssistant.getPetOwner());
                System.out.println("Lab assistant : " + labAssistant.getPetType());
                Object[] row = new Object[4];
                row[0] = labAssistant.getPetOwner();
                row[1] = labAssistant.getPetType();
                row[2] = labAssistant.getHealthCamp();
                row[3] = labAssistant.getLabResultStatus() == null ? "N/A" : labAssistant.getLabResultStatus();
                tablemodel.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbllabassitant = new javax.swing.JTable();
        lbllabresult = new javax.swing.JLabel();
        txtlabresult = new javax.swing.JTextField();
        btnchangestatus = new javax.swing.JButton();

        tbllabassitant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pet Owner", "Pet Type", "Health Camp", "Test Result"
            }
        ));
        jScrollPane1.setViewportView(tbllabassitant);

        lbllabresult.setText("lab result ");

        btnchangestatus.setText("ChangeStatus");
        btnchangestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangestatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnchangestatus)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbllabresult, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtlabresult, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllabresult)
                    .addComponent(txtlabresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnchangestatus)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnchangestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangestatusActionPerformed
        // TODO add your handling code here:
        String status = txtlabresult.getText();
        for(LabAssistant labAssistant: system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            system.getLabAssistantDirectory().updateLabAssistantTestResult(labAssistant, status);
            System.out.println("Lab result updated successfully");
        }
        for(LabAssistant labAssistant: system.getLabAssistantDirectory().getLabAssistantDirectory()) {
            for(PetVolunteer petVolunteer: system.getPetVolunteerDirectory().getPetVolunteerDirectory()) {
                if(petVolunteer.getName().equals(labAssistant.getPetOwner())){
                    system.getPetVolunteerDirectory().updatePetVolunteerLabStatus(petVolunteer, status);
                    System.out.println("Lab status updated successfully");
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Successfully updated lab results");
        populateTable();
    }//GEN-LAST:event_btnchangestatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchangestatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllabresult;
    private javax.swing.JTable tbllabassitant;
    private javax.swing.JTextField txtlabresult;
    // End of variables declaration//GEN-END:variables
}
