/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import ReliefSystem.Ecosystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 18578
 */
public class ManagePetVolunteer extends javax.swing.JPanel {

    /**
     * Creates new form ManagePetVolunteer
     */
    JPanel userProcessContainer;
    Ecosystem system;
    public ManagePetVolunteer(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblpetvol = new javax.swing.JTable();
        lblPetVolunteer = new javax.swing.JLabel();
        lblPetVolunteerImg = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblpetvol.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tblpetvol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name ", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblpetvol);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 409, 100));

        lblPetVolunteer.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblPetVolunteer.setForeground(new java.awt.Color(0, 153, 153));
        lblPetVolunteer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPetVolunteer.setText("MANAGE PET VOLUNTEER");
        add(lblPetVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 420, 50));

        lblPetVolunteerImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/petVolunteer.jpg"))); // NOI18N
        add(lblPetVolunteerImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 331, 280));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 153, 153));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 230, 30));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 153, 153));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 220, 30));

        lblUserName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 153, 153));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("User Name");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 230, 30));

        txtUserName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 153, 153));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 190, 30));

        txtName.setForeground(new java.awt.Color(0, 153, 153));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 190, 30));

        jPasswordField1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 153, 153));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 190, 30));

        btnSubmit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 153, 153));
        btnSubmit.setText("SUBMIT");
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 470, 90, -1));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        btnView.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 153, 153));
        btnView.setText("VIEW");
        btnView.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 50, -1));

        btnDelete.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 153, 153));
        btnDelete.setText("DELETE");
        btnDelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 470, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPetVolunteer;
    private javax.swing.JLabel lblPetVolunteerImg;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblpetvol;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
