/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import ReliefSystem.Ecosystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author divya
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysadminWorkArea
     */
    JPanel userProcessContainer;
    Ecosystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        manageHospital = new javax.swing.JPanel();
        lblHospNetwork = new javax.swing.JLabel();
        txtHospitalNetwork = new javax.swing.JTextField();
        manageSponsors = new javax.swing.JPanel();
        lblSponsors = new javax.swing.JLabel();
        txtManageSponsors = new javax.swing.JTextField();
        manageVet = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtManagePetVolunteer = new javax.swing.JTextField();
        manageHealthCamp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtManageHealthCamp = new javax.swing.JTextField();
        manageFundRaisongAgency = new javax.swing.JPanel();
        lblFundRaiser = new javax.swing.JLabel();
        txtFundRaisingAgency = new javax.swing.JTextField();

        sidePane.setBackground(new java.awt.Color(0, 153, 153));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageHospital.setBackground(new java.awt.Color(0, 204, 204));

        lblHospNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hospital-icon.jpg"))); // NOI18N

        txtHospitalNetwork.setBackground(new java.awt.Color(0, 204, 204));
        txtHospitalNetwork.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtHospitalNetwork.setText("Manage Hospital Network");
        txtHospitalNetwork.setBorder(null);
        txtHospitalNetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtHospitalNetworkMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageHospitalLayout = new javax.swing.GroupLayout(manageHospital);
        manageHospital.setLayout(manageHospitalLayout);
        manageHospitalLayout.setHorizontalGroup(
            manageHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageHospitalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHospNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHospitalNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageHospitalLayout.setVerticalGroup(
            manageHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHospNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageHospitalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHospitalNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidePane.add(manageHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 40));

        manageSponsors.setBackground(new java.awt.Color(0, 204, 204));


        txtManageSponsors.setBackground(new java.awt.Color(0, 204, 204));
        txtManageSponsors.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtManageSponsors.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtManageSponsors.setText("Manage Sponsors");
        txtManageSponsors.setBorder(null);
        txtManageSponsors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtManageSponsorsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageSponsorsLayout = new javax.swing.GroupLayout(manageSponsors);
        manageSponsors.setLayout(manageSponsorsLayout);
        manageSponsorsLayout.setHorizontalGroup(
            manageSponsorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageSponsorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSponsors, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtManageSponsors, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        manageSponsorsLayout.setVerticalGroup(
            manageSponsorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSponsors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageSponsorsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtManageSponsors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidePane.add(manageSponsors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 260, -1));

        manageVet.setBackground(new java.awt.Color(0, 204, 204));
        

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pet_owner.png"))); // NOI18N

        txtManagePetVolunteer.setBackground(new java.awt.Color(0, 204, 204));
        txtManagePetVolunteer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtManagePetVolunteer.setText("Manage Pet Volunteer");
        txtManagePetVolunteer.setBorder(null);
        txtManagePetVolunteer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtManagePetVolunteerMousePressed(evt);
            }
        });
        

        javax.swing.GroupLayout manageVetLayout = new javax.swing.GroupLayout(manageVet);
        manageVet.setLayout(manageVetLayout);
        manageVetLayout.setHorizontalGroup(
            manageVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageVetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtManagePetVolunteer, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageVetLayout.setVerticalGroup(
            manageVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageVetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtManagePetVolunteer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidePane.add(manageVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        manageHealthCamp.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/health-camp.png"))); // NOI18N

        txtManageHealthCamp.setBackground(new java.awt.Color(0, 204, 204));
        txtManageHealthCamp.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtManageHealthCamp.setText("Manage Health Camp");
        txtManageHealthCamp.setBorder(null);
        txtManageHealthCamp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtManageHealthCampMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageHealthCampLayout = new javax.swing.GroupLayout(manageHealthCamp);
        manageHealthCamp.setLayout(manageHealthCampLayout);
        manageHealthCampLayout.setHorizontalGroup(
            manageHealthCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageHealthCampLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtManageHealthCamp, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageHealthCampLayout.setVerticalGroup(
            manageHealthCampLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageHealthCampLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtManageHealthCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidePane.add(manageHealthCamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        manageFundRaisongAgency.setBackground(new java.awt.Color(0, 204, 204));
        

        lblFundRaiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundraising.png"))); // NOI18N

        txtFundRaisingAgency.setBackground(new java.awt.Color(0, 204, 204));
        txtFundRaisingAgency.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtFundRaisingAgency.setText("Manage Fundraising Agency");
        txtFundRaisingAgency.setBorder(null);
        txtFundRaisingAgency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFundRaisingAgencyMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageFundRaisongAgencyLayout = new javax.swing.GroupLayout(manageFundRaisongAgency);
        manageFundRaisongAgency.setLayout(manageFundRaisongAgencyLayout);
        manageFundRaisongAgencyLayout.setHorizontalGroup(
            manageFundRaisongAgencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageFundRaisongAgencyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFundRaiser, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFundRaisingAgency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        manageFundRaisongAgencyLayout.setVerticalGroup(
            manageFundRaisongAgencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFundRaiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageFundRaisongAgencyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFundRaisingAgency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidePane.add(manageFundRaisongAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, -1));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(sidePane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 633, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePane, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospitalNetworkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHospitalNetworkMousePressed
        // TODO add your handling code here:
        ManageHospitalNetwork manageHospitalNetworkJPanel = new ManageHospitalNetwork(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageHospitals", manageHospitalNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_txtHospitalNetworkMousePressed

    private void txtManagePetVolunteerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtManagePetVolunteerMousePressed
        // TODO add your handling code here:
        ManagePetVolunteer managePetVolunteerJPanel = new ManagePetVolunteer(userProcessContainer, ecosystem);
        userProcessContainer.add("ManagePetVolunteers", managePetVolunteerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_txtManagePetVolunteerMousePressed

    private void txtManageHealthCampMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtManageHealthCampMousePressed
        // TODO add your handling code here:
        ManageHealthCamp manageHealthCampJPanel = new ManageHealthCamp(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageHealthCamp", manageHealthCampJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_txtManageHealthCampMousePressed

    private void txtFundRaisingAgencyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFundRaisingAgencyMousePressed
        // TODO add your handling code here:
        ManageFundAgency manageFundRaisingAgencyJPanel = new ManageFundAgency(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageFundRaisingAgency", manageFundRaisingAgencyJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_txtFundRaisingAgencyMousePressed

    private void txtManageSponsorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtManageSponsorsMousePressed
        // TODO add your handling code here:
        ManageSponsor manageSponsorJPanel = new ManageSponsor(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageSponsors", manageSponsorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_txtManageSponsorsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFundRaiser;
    private javax.swing.JLabel lblHospNetwork;
    private javax.swing.JLabel lblSponsors;
    private javax.swing.JPanel manageFundRaisongAgency;
    private javax.swing.JPanel manageHealthCamp;
    private javax.swing.JPanel manageHospital;
    private javax.swing.JPanel manageSponsors;
    private javax.swing.JPanel manageVet;
    private javax.swing.JPanel sidePane;
    private javax.swing.JTextField txtFundRaisingAgency;
    private javax.swing.JTextField txtHospitalNetwork;
    private javax.swing.JTextField txtManageHealthCamp;
    private javax.swing.JTextField txtManagePetVolunteer;
    private javax.swing.JTextField txtManageSponsors;
    // End of variables declaration//GEN-END:variables
}
