/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import ReliefSystem.DB4oUtil.DB4OUtil;
import ReliefSystem.Ecosystem;
import ReliefSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.time.Duration;
import javax.swing.JPanel;

/**
 *
 * @author 18578
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Ecosystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setSize(1680, 1050);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        lblUserName1 = new javax.swing.JLabel();
        lblSysAdminImg = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        lblDogImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        ControlPanel.setBackground(new java.awt.Color(255, 255, 255));
        ControlPanel.setMinimumSize(new java.awt.Dimension(350, 273));
        ControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtusername.setForeground(new java.awt.Color(0, 153, 153));
        txtusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        ControlPanel.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 140, 30));

        txtpassword.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(0, 153, 153));
        txtpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        ControlPanel.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 140, 30));

        btnlogin.setBackground(new java.awt.Color(255, 255, 255));
        btnlogin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(0, 153, 153));
        btnlogin.setText("LOGIN");
        btnlogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        ControlPanel.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 90, -1));

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        ControlPanel.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key_resized.jpg"))); // NOI18N
        ControlPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 50, 30));

        lblUserName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-profile-icon-free-vector.jpg"))); // NOI18N
        ControlPanel.add(lblUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, 30));

        lblSysAdminImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Pictures\\AED Project\\adminlogo.jfif")); // NOI18N
        lblSysAdminImg.setText("jLabel2");
        ControlPanel.add(lblSysAdminImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 190));

        jSplitPane1.setLeftComponent(ControlPanel);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new java.awt.CardLayout());

        lblDogImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\divya\\Pictures\\AED Project\\Sysadmin.png")); // NOI18N
        container.add(lblDogImg, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        UserAccount useraccount = system.getUserAccountDirectory().authenticateUser(txtusername.getText(), txtpassword.getText());
        
        CardLayout crdLyt = (CardLayout) container.getLayout();
        container.add("Login", useraccount.getRole().createWorkArea(container, useraccount, system));
        crdLyt.next(container);
        btnlogout.setEnabled(true);
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        btnlogout.setEnabled(false);
        txtusername.setEnabled(true);
        txtpassword.setEnabled(true);
        btnlogin.setEnabled(true);

        txtusername.setText("");
        txtpassword.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        StartScreen screen = new StartScreen();
        screen.setVisible(true);
        try{
        for (int row = 0; row <=100; row++) {
                Thread.sleep(10);
                screen.loadingNumber.setText(Integer.toString(row)+"%");
                screen.loadingprogressBar.setValue(row);
                if (row == 100) {
                screen.setVisible(false);
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
                }
        }
        }catch (Exception e){};
        
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainJFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JPanel container;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblDogImg;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSysAdminImg;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
